# Generated by Django 3.1.1 on 2020-09-16 22:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre de la categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion de la categoria')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, unique=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Color Producto',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre de la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre del proveedor')),
                ('email', models.EmailField(max_length=100, verbose_name='email proveedor')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefonos')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre de la sub-categoria')),
            ],
            options={
                'verbose_name': 'Sub_Categoria',
                'verbose_name_plural': 'Sub_Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion del producto')),
                ('unit', models.CharField(choices=[('SIZE_NUMBER', 'Talle por numero'), ('SIZE', 'Talle por letra')], max_length=11, verbose_name='Unidad de medida')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], max_length=1, verbose_name='Genero')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en almacen')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio venta')),
                ('num_sale', models.PositiveIntegerField(default=0, verbose_name='Numero de ventas')),
                ('main_image', models.ImageField(upload_to='producto', verbose_name='imagen principal')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 4')),
                ('anulate', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('offer', models.BooleanField(default=False, verbose_name='En oferta')),
                ('discount', models.PositiveIntegerField(verbose_name='Descuento')),
                ('comment', models.TextField(blank=True, max_length=150, verbose_name='comentarios del producto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('color', models.ManyToManyField(to='product.Colors')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='marca',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.provider'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategoria'),
        ),
    ]
