# Generated by Django 3.1.1 on 2020-09-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200917_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.PositiveIntegerField(verbose_name='size number')),
            ],
            options={
                'verbose_name': 'SizeNumber',
                'verbose_name_plural': 'SizeNumbers',
            },
        ),
        migrations.RemoveField(
            model_name='size',
            name='size_number',
        ),
        migrations.AddField(
            model_name='product',
            name='sizeNumber',
            field=models.ManyToManyField(to='product.SizeNumber'),
        ),
    ]
