# Generated by Django 3.1.1 on 2020-09-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200917_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Descuento'),
        ),
    ]
