# Generated by Django 3.1.1 on 2020-09-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200917_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='product.Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizeNumber',
            field=models.ManyToManyField(blank=True, to='product.SizeNumber'),
        ),
    ]
