# Generated by Django 3.1.1 on 2020-09-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200917_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Talle por numero'), (1, 'Talle por letra')], max_length=30, verbose_name='Unidad de medida'),
        ),
    ]
