# Generated by Django 3.1.1 on 2020-09-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200917_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[(0, 'Talle por numero'), (1, 'Talle por letra')], max_length=1, verbose_name='Unidad de medida'),
        ),
    ]
