# Generated by Django 3.1.1 on 2020-09-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200917_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('0', 'numero'), ('1', 'letra')], max_length=1, verbose_name='Unidad de medida'),
        ),
    ]
