# Generated by Django 3.1.1 on 2020-09-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200917_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ZERO', 'numero'), ('ONE', 'letra')], max_length=5, verbose_name='Unidad de medida'),
        ),
    ]
