# Generated by Django 3.1.1 on 2020-09-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200917_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('n', 'numero'), ('l', 'letra')], max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
