# Generated by Django 3.1.1 on 2020-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200917_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Number', 'Number'), ('Letter', 'Letter')], max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
