# Generated by Django 3.1.1 on 2020-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200918_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Numero', 'Numero'), ('Letra', 'Letra')], max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
