# Generated by Django 3.1.1 on 2020-09-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200918_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Descuento'),
        ),
    ]
