# Generated by Django 3.1.1 on 2020-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_price_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_categoria',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categoria',
            field=models.ManyToManyField(to='product.SubCategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='precio de Descuento'),
        ),
    ]
