# Generated by Django 3.1.1 on 2020-09-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200922_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_categoria',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='category',
            field=models.ManyToManyField(to='product.Category'),
        ),
    ]
