# Generated by Django 3.1.1 on 2020-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200925_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categoria',
            field=models.ManyToManyField(to='product.SubCategoria'),
        ),
    ]
