# Generated by Django 3.1.1 on 2020-09-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200925_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.subcategoria'),
            preserve_default=False,
        ),
    ]
