# Generated by Django 3.1.1 on 2020-10-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20200926_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=2121212, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(blank=True, default=False, verbose_name='En oferta'),
        ),
    ]
