# Generated by Django 3.1.1 on 2020-10-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20201003_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=0, max_length=13, unique=True),
        ),
    ]
