# Generated by Django 3.1.1 on 2020-10-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200916_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
