# Generated by Django 3.1.1 on 2020-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_carshop_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='nombre producto'),
        ),
    ]
