# Generated by Django 3.1.1 on 2020-10-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_carshop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Productos'),
            preserve_default=False,
        ),
    ]
